version: '3.9'


services:
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
    - 3306:3306
    volumes:
      - ./dataab/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}

  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"